### ISSUE TITLE
could u make it compiled my computer is too weak to download vs and compile it

### ISSUE THREAD

**Issue by ghost** [N3agu/Akame-Loader#1]

**Comment by Wtf-Is-This-x1337** [comment]
I will make add binaries in the next update

**Comment by N3agu** [comment]
Hello! Sadly, I can't create binaries for this project because this is a loader, not a builder.
You need to use your own shellcode (generate it and integrate it into the source code) to build the project, you can't use my executable because that will contain my payload (with my settings: IP, Port, functions).

If you can't download / use visual studio, you should copy Akame.cpp and compile it with g++, I will probably add a command for it in the future updates.
