### ISSUE TITLE
Could you add support to x86 framework?

### ISSUE THREAD

**Issue by RookieTerry** [N3agu/Akame-Loader#3]
The framework of my shellcode is 32 bit,and I hope you can add support to it.Thank you!

**Comment by N3agu** [comment]
1. The loader can load x86 shellcodes, but can't run on 32 bit systems
2. I think that most computers are running 64 bit systems these days
3. Keep in mind that detection rate is much higher for x86 windows applications

To change the loader to x86 you only need to change the project settings (guide here: https://github.com/Wtf-Is-This-x1337/Akame-Loader#how-to-build), but change the platform to "x86", and maybe take a look at the KUSER_SHARED_DATA structure, because I use offsets to get information about the “tick count” and it may be different ones for 32 bit systems.

You can get more information about KUSER_SHARED_DATA here: https://www.geoffchappell.com/studies/windows/km/ntoskrnl/inc/api/ntexapi_x/kuser_shared_data/index.htm

**Comment by RookieTerry** [comment]
I use x64 framework in vs2022 and compile it,but the target machine can't get online.

**Comment by N3agu** [comment]
Did you follow all the instructions from the guide, including generating and changing the payload, the IV and the key from Akame.cpp?
